package com.stkj.aoxin.weight.base.greendao.generate;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.stkj.aoxin.weight.setting.model.FacePassPeopleInfo;
import com.stkj.aoxin.weight.setting.model.FoodInfoTable;

import com.stkj.aoxin.weight.base.greendao.generate.FacePassPeopleInfoDao;
import com.stkj.aoxin.weight.base.greendao.generate.FoodInfoTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig facePassPeopleInfoDaoConfig;
    private final DaoConfig foodInfoTableDaoConfig;

    private final FacePassPeopleInfoDao facePassPeopleInfoDao;
    private final FoodInfoTableDao foodInfoTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        facePassPeopleInfoDaoConfig = daoConfigMap.get(FacePassPeopleInfoDao.class).clone();
        facePassPeopleInfoDaoConfig.initIdentityScope(type);

        foodInfoTableDaoConfig = daoConfigMap.get(FoodInfoTableDao.class).clone();
        foodInfoTableDaoConfig.initIdentityScope(type);

        facePassPeopleInfoDao = new FacePassPeopleInfoDao(facePassPeopleInfoDaoConfig, this);
        foodInfoTableDao = new FoodInfoTableDao(foodInfoTableDaoConfig, this);

        registerDao(FacePassPeopleInfo.class, facePassPeopleInfoDao);
        registerDao(FoodInfoTable.class, foodInfoTableDao);
    }
    
    public void clear() {
        facePassPeopleInfoDaoConfig.clearIdentityScope();
        foodInfoTableDaoConfig.clearIdentityScope();
    }

    public FacePassPeopleInfoDao getFacePassPeopleInfoDao() {
        return facePassPeopleInfoDao;
    }

    public FoodInfoTableDao getFoodInfoTableDao() {
        return foodInfoTableDao;
    }

}
